graph TD
    classDef default white-space:nowrap;

    A0("onPageShow")
    --> A1("initWebSocket")
    A1 --> A2("on('open')")
    A1 --> A3("on('message')")
    A1 --> A4("on('error')")
    A1 --> A5("on('close')")

    D1("on('message')") --> D2("handleWebSocketMessage")
    D2("handleWebSocketMessage") --> D3{"判断msg.type"}
    D3 --"如果=== 'history'"--> D4("parseMessageArray")
    D3 --"如果=== 'newMessage'"--> D5("更新messageList状态")
    D4 --> D5
    D5 --> D6("刷新页面")

    C0("onSubmit发送新消息") --> C2("sendMessage")
    C1("onClick发送新消息") --> C2("sendMessage")
    C2 --> C3("webSocket.WebSocket实例.send")
    C3 --> C4("向服务端发送消息")

    B0("onPageHide") --> B1("closeWebSocket")